# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: account.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\raccount.proto\x12\x07\x61\x63\x63ount\"=\n\x0e\x41\x63\x63ountRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06userId\x18\x02 \x01(\x05\x12\x0f\n\x07\x62\x61lance\x18\x03 \x01(\x02\"#\n\x11NewAccountRequest\x12\x0e\n\x06userId\x18\x01 \x01(\x05\"O\n\x0f\x41\x63\x63ountResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06userId\x18\x02 \x01(\x05\x12\x0f\n\x07\x62\x61lance\x18\x03 \x01(\x02\x12\x0f\n\x07message\x18\x04 \x01(\t\"O\n\x10\x41\x63\x63ountsResponse\x12*\n\x08\x61\x63\x63ounts\x18\x01 \x03(\x0b\x32\x18.account.AccountResponse\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x07\n\x05\x45mpty\"(\n\x16GetUserAccountsRequest\x12\x0e\n\x06userId\x18\x01 \x01(\x05\"#\n\x15GetAccountByIdRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"@\n\x11\x41\x64\x64\x41\x63\x63ountRequest\x12+\n\x07\x61\x63\x63ount\x18\x01 \x01(\x0b\x32\x1a.account.NewAccountRequest\"@\n\x14UpdateAccountRequest\x12(\n\x07\x61\x63\x63ount\x18\x01 \x01(\x0b\x32\x17.account.AccountRequest\"\"\n\x14\x44\x65leteAccountRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x32\x86\x03\n\x0e\x41\x63\x63ountService\x12M\n\x0fGetUserAccounts\x12\x1f.account.GetUserAccountsRequest\x1a\x19.account.AccountsResponse\x12J\n\x0eGetAccountById\x12\x1e.account.GetAccountByIdRequest\x1a\x18.account.AccountResponse\x12\x45\n\rCreateAccount\x12\x1a.account.AddAccountRequest\x1a\x18.account.AccountResponse\x12H\n\rUpdateAccount\x12\x1d.account.UpdateAccountRequest\x1a\x18.account.AccountResponse\x12H\n\rDeleteAccount\x12\x1d.account.DeleteAccountRequest\x1a\x18.account.AccountResponseB\x17\xaa\x02\x14\x41\x63\x63ountService.Protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'account_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\024AccountService.Proto'
  _globals['_ACCOUNTREQUEST']._serialized_start=26
  _globals['_ACCOUNTREQUEST']._serialized_end=87
  _globals['_NEWACCOUNTREQUEST']._serialized_start=89
  _globals['_NEWACCOUNTREQUEST']._serialized_end=124
  _globals['_ACCOUNTRESPONSE']._serialized_start=126
  _globals['_ACCOUNTRESPONSE']._serialized_end=205
  _globals['_ACCOUNTSRESPONSE']._serialized_start=207
  _globals['_ACCOUNTSRESPONSE']._serialized_end=286
  _globals['_EMPTY']._serialized_start=288
  _globals['_EMPTY']._serialized_end=295
  _globals['_GETUSERACCOUNTSREQUEST']._serialized_start=297
  _globals['_GETUSERACCOUNTSREQUEST']._serialized_end=337
  _globals['_GETACCOUNTBYIDREQUEST']._serialized_start=339
  _globals['_GETACCOUNTBYIDREQUEST']._serialized_end=374
  _globals['_ADDACCOUNTREQUEST']._serialized_start=376
  _globals['_ADDACCOUNTREQUEST']._serialized_end=440
  _globals['_UPDATEACCOUNTREQUEST']._serialized_start=442
  _globals['_UPDATEACCOUNTREQUEST']._serialized_end=506
  _globals['_DELETEACCOUNTREQUEST']._serialized_start=508
  _globals['_DELETEACCOUNTREQUEST']._serialized_end=542
  _globals['_ACCOUNTSERVICE']._serialized_start=545
  _globals['_ACCOUNTSERVICE']._serialized_end=935
# @@protoc_insertion_point(module_scope)
