# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: account.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\raccount.proto\x12\x07\x61\x63\x63ount\"(\n\x16GetUserAccountsRequest\x12\x0e\n\x06userId\x18\x01 \x01(\x05\"#\n\x15GetAccountByIdRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"#\n\x11\x41\x64\x64\x41\x63\x63ountRequest\x12\x0e\n\x06userId\x18\x01 \x01(\x05\"C\n\x14UpdateAccountRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06userId\x18\x02 \x01(\x05\x12\x0f\n\x07\x62\x61lance\x18\x03 \x01(\x02\"\"\n\x14\x44\x65leteAccountRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"E\n\x0f\x41\x63\x63ountResponse\x12&\n\x07\x61\x63\x63ount\x18\x01 \x01(\x0b\x32\x10.account.AccountH\x00\x88\x01\x01\x42\n\n\x08_account\"6\n\x10\x41\x63\x63ountsResponse\x12\"\n\x08\x61\x63\x63ounts\x18\x01 \x03(\x0b\x32\x10.account.Account\"6\n\x07\x41\x63\x63ount\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06userId\x18\x02 \x01(\x05\x12\x0f\n\x07\x62\x61lance\x18\x03 \x01(\x02\x32\x86\x03\n\x0e\x41\x63\x63ountService\x12M\n\x0fGetUserAccounts\x12\x1f.account.GetUserAccountsRequest\x1a\x19.account.AccountsResponse\x12J\n\x0eGetAccountById\x12\x1e.account.GetAccountByIdRequest\x1a\x18.account.AccountResponse\x12\x45\n\rCreateAccount\x12\x1a.account.AddAccountRequest\x1a\x18.account.AccountResponse\x12H\n\rUpdateAccount\x12\x1d.account.UpdateAccountRequest\x1a\x18.account.AccountResponse\x12H\n\rDeleteAccount\x12\x1d.account.DeleteAccountRequest\x1a\x18.account.AccountResponseB\x11\xaa\x02\x0eProtos.Accountb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'account_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\016Protos.Account'
  _globals['_GETUSERACCOUNTSREQUEST']._serialized_start=26
  _globals['_GETUSERACCOUNTSREQUEST']._serialized_end=66
  _globals['_GETACCOUNTBYIDREQUEST']._serialized_start=68
  _globals['_GETACCOUNTBYIDREQUEST']._serialized_end=103
  _globals['_ADDACCOUNTREQUEST']._serialized_start=105
  _globals['_ADDACCOUNTREQUEST']._serialized_end=140
  _globals['_UPDATEACCOUNTREQUEST']._serialized_start=142
  _globals['_UPDATEACCOUNTREQUEST']._serialized_end=209
  _globals['_DELETEACCOUNTREQUEST']._serialized_start=211
  _globals['_DELETEACCOUNTREQUEST']._serialized_end=245
  _globals['_ACCOUNTRESPONSE']._serialized_start=247
  _globals['_ACCOUNTRESPONSE']._serialized_end=316
  _globals['_ACCOUNTSRESPONSE']._serialized_start=318
  _globals['_ACCOUNTSRESPONSE']._serialized_end=372
  _globals['_ACCOUNT']._serialized_start=374
  _globals['_ACCOUNT']._serialized_end=428
  _globals['_ACCOUNTSERVICE']._serialized_start=431
  _globals['_ACCOUNTSERVICE']._serialized_end=821
# @@protoc_insertion_point(module_scope)
